# Generated by Django 4.2 on 2024-03-24 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(db_column='CardID', primary_key=True, serialize=False)),
                ('question', models.TextField(db_column='Question')),
                ('answer', models.TextField(db_column='Answer')),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_column='UploadDate')),
                ('views', models.IntegerField(db_column='Views', default=0)),
                ('favorites', models.IntegerField(db_column='Favorites', default=0)),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'db_table': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(db_column='TagID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('user_name', models.TextField(db_column='UserName', max_length=100)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='CardTags',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('card', models.ForeignKey(db_column='CardID', on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('tag', models.ForeignKey(db_column='TagID', on_delete=django.db.models.deletion.CASCADE, to='cards.tag')),
            ],
            options={
                'verbose_name': 'Связь карточка-тег',
                'verbose_name_plural': 'Связи карточка-тег',
                'db_table': 'CardTags',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='category_id',
            field=models.ForeignKey(db_column='CategoryID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.category'),
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(related_name='cards', through='cards.CardTags', to='cards.tag'),
        ),
    ]
